### PR TITLE
Added Programming languages with Z

### PR DESCRIPTION
**Pull request by itsvipindev**

### CODE REVIEW

**Review by chilarai — APPROVED** [review]
Thanks

**Comment by itsvipindev** [comment]
Thank you a lot this was my first contribution

**Comment by chilarai** [comment]
This is awesome @itsvipindev. You did great and hope you learn a lot

**Comment by itsvipindev** [comment]
Yes sir i will contribute more on this project will every pull request on this project will count ?

**Comment by chilarai** [comment]
Yes. it will count

**Pull request merged**
